### ISSUE TITLE
how to use in a browser env ?

### ISSUE THREAD

**Issue by ctf0** [ronomon/zip#1]
it might be a dump question, but is there any way to incorporate the lib with uploads from the browser, so we can check files before its even sent to the server ?

**Comment by jorangreef** [comment]
Thanks @ctf0 , it's designed for a Node environment.

You could fork the module and get it to run in the browser. You would need to read through `index.js` and replace the Node dependencies:

* Node.fs.constants
* Node.zlib (only if you need to inflate, not required for decoding headers)
* Buffer

**Comment by ctf0** [comment]
thanx for your quick reply, sadly i have no exp with node 😢 , still thanx for ur hard work 🥇
